# .github/workflows/ci.yml
name: Maven Build, Test, and SonarCloud Analysis

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        shell: bash
        run: mvn clean install

      - name: Run tests
        shell: bash
        run: mvn test

      # Install SonarScanner
      - name: Install SonarScanner
        shell: bash
        run: |
          wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner.zip -d $HOME
          echo "$HOME/sonar-scanner-4.6.2.2472-linux/bin" >> $GITHUB_PATH

      # SonarCloud Scan Step
      - name: SonarCloud Scan
        shell: bash
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PATH: ${{ runner.home }}/sonar-scanner-4.6.2.2472-linux/bin:${{ env.PATH }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=James_Busari_as02-test-secure-api-j-p_public \
            -Dsonar.organization=James_Busari \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
